### ISSUE TITLE
Output metrics to prometheus 

### ISSUE THREAD

**Issue by toan-hf** [tagomoris/fluent-plugin-flowcounter#26]
First of all, thank you for this great plugin. I am currently facing the challenge to calculate how many log message & how much space for each of them. Supposedly, it can be resolved by this plugin. 
However i want to output those metrics into Prometheus instead of stdout. I am thinking to send all of them into 1 message queue place and do the scraping  / consume from that queue. But feeling it is a bit over engineering. So my question is 
Do we have any solution to output those metrics directly to Prometheus ? 

Thanks & Looking forward to hearing from your advice

**Comment by tagomoris** [comment]
This is the issue/bug tracker, not for the Q&A or consultation about how to use this plugin.
Please find anywhere else for such purposes.
